# Generated by Django 4.1.13 on 2024-09-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('electricity', models.FloatField()),
                ('natural_gas', models.FloatField()),
                ('biomass', models.FloatField()),
                ('coal', models.FloatField()),
                ('heating_oil', models.FloatField()),
                ('lpg', models.FloatField()),
                ('total_co2e', models.FloatField()),
            ],
        ),
    ]
