# Generated by Django 4.1.13 on 2024-09-02 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_calculator', '0002_carbonfootprinthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonfootprinthistory',
            name='date',
        ),
        migrations.AddField(
            model_name='carbonfootprinthistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carbonfootprinthistory',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
